/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ProjetoFinal;

import controller.ProjetoController;
import controller.TarefaController;
import java.sql.Connection;
import java.sql.Date;
import model.Projeto;
import model.Tarefa;
import util.ConnectionFactory;


public class App {

    public static void main(String[] args) {
        //cria projeto com um nome
        //Projeto p = new Projeto();
        //p.setNome("Jhonny Alves de Souza Azevedo");
        //p.setId(1);
       
        
        //conecta com o banco
        ProjetoController pc = new ProjetoController();
        pc.removeById(1);
        //imprimir
        System.out.println("Número de projetos "+ pc.getAll().size());
       
        //Tarefa t = new Tarefa();
        
        //t.setIdProjetos(1);
        //t.setNome("Mylena");
       
        
       // TarefaController tc = new TarefaController();
        //tc.removeById(2);
        //System.out.println("Número de tarefas "+ tc.getAll(1).size());

    }
}
